# Generated by Django 3.2 on 2021-05-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('team_member', models.CharField(max_length=100)),
                ('needed_member', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('national_id_image', models.ImageField(default='', upload_to='tourshare/images')),
                ('create_user_image', models.ImageField(default='', upload_to='tourshare/images')),
            ],
        ),
    ]
