# Generated by Django 3.2 on 2021-05-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourshare', '0003_join_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_user',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
