# Generated by Django 3.2 on 2021-06-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourshare', '0004_join_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_user',
            name='fblink',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='create_user',
            name='twitterlink',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='join_user',
            name='email',
            field=models.EmailField(default='0', max_length=100),
        ),
    ]
