# Generated by Django 3.2 on 2021-06-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourshare', '0005_auto_20210626_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_user',
            name='fblink',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='join_user',
            name='twitterlink',
            field=models.CharField(default='', max_length=300),
        ),
    ]
